//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Money_Donation
    {
        public int Id_money { get; set; }
        public string Full_name { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
