//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int Id_partners { get; set; }
        public string Name_partners { get; set; }
        public Nullable<decimal> National_number { get; set; }
        public Nullable<System.DateTime> Year_partners { get; set; }
        public string Description_partners { get; set; }
        public Nullable<int> state { get; set; }
        public string Id { get; set; }
        public string Email { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
