//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int Id_recommendation { get; set; }
        public string Address_recommendation { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string Details { get; set; }
        public Nullable<int> members { get; set; }
        public Nullable<int> workers { get; set; }
        public Nullable<int> fixed_income { get; set; }
        public string name { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> done_rec { get; set; }
    }
}
