//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int Id_volunteer { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string Full_name { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Details { get; set; }
        public string Academic_degree { get; set; }
        public Nullable<int> State_volunteer { get; set; }
        public string Email { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
